[package]
name = "raytracing-rust"
version = "0.1.0"
authors = ["David Elder <elddm1@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
clippy = {version = "*", optional = true}

[lib]
name = "raytracer"
path = "src/lib.rs"

[profile.release]
debug = true